---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:5.5.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./src/test/resources/postgres:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]
  pamad:
    depends_on:
      - postgres
      - broker
      - zookeeper
    image: ghcr.io/navikt/pam-ad:21.267.153931
    ports:
      - 127.0.0.1:9001:9001
    environment:
      - DB_PASSWORD=pamad
      - DB_USERNAME=pamad
      - DB_DRIVER=org.postgresql.Driver
      - DB_HOST=postgres
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - SCHEDULER_ENABLED=true
      - PUSHADTOKAFKA_ENABLED=false
      - IMPORTAPI_ENABLED=true
      - IMPORTAPI_FEED_URL=http://importapi:9028/stillingsimport/internal/adstates
  importapi:
    build: .
    depends_on:
      - postgres
      - broker
      - pamad
    ports:
      - "9028:9028"
    environment:
      DB_PASSWORD: importapi
      DB_USERNAME: importapi
      DB_DRIVER: org.postgresql.Driver
      DB_HOST: 'postgres'
      KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'
