apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-import-api
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9028
  liveness:
    path: /stillingsimport/internal/isAlive
    initialDelay: 40
  readiness:
    path: /stillingsimport/internal/isReady
    initialDelay: 40
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: false
  webproxy: false
  prometheus:
    enabled: true
    path: /stillingsimport/internal/prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  filesFrom:
    - secret: pam-import-api-env-secret
      mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: DB_DRIVER
      value: "org.postgresql.Driver"
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {{ kafka_bootstrap_servers }}
  gcp:
    sqlInstances:
      - name: import-api-stilling
        type: POSTGRES_11
        tier: db-custom-2-7680
        diskType: SSD
        highAvailability: true
        diskSize: 20
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: importapi
            envVarPrefix: DB
        cascadingDelete: false
