apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-import-api
  namespace: default
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9028
  liveness:
    path: /stillingsimport/internal/isAlive
    initialDelay: 20
  readiness:
    path: /stillingsimport/internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: false
  webproxy: false
  prometheus:
    enabled: true
    path: /stillingsimport/internal/prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  filesFrom:
    - secret: pam-er-import-env-secret
      mountPath: /var/run/secrets/nais.io/vault
  gcp:
    sqlInstances:
      - name: import-api-stilling
        type: POSTGRES_11
        diskType: SSD
        highAvailability: true
        diskSize: 20
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: import-api
            envVarPrefix: DB
        cascadingDelete: false
