apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-import-api
  namespace: default
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9028
  liveness:
    path: /stillingsimport/internal/isAlive
    initialDelay: 20
  readiness:
    path: /stillingsimport/internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 1
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ serviceuser-credentials }}
        mountPath: /secrets/pamimportapi/serviceuser/credentials
      - kvPath: {{ oracle-credentials }}
        mountPath: /secrets/pamimportapi/oracle/credentials
      - kvPath: {{ oracle-config }}
        mountPath: /secrets/pamimportapi/oracle/config
      - kvPath: {{ pamimportapi-env }}
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: false
  prometheus:
    enabled: true
    path: /stillingsimport/prometheus
  ingresses:
    - {{ ingress }}
    - {{ ingress-tjenester }}
