apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pam-import-api
  namespace: teampam
  labels:
    team: teampam
spec:
  port: 9028
  liveness:
    path: /stillingsimport/internal/isAlive
    initialDelay: 40
  readiness:
    path: /stillingsimport/internal/isReady
    initialDelay: 40
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 320Mi
  vault:
    enabled: false
  webproxy: false
  leaderElection: true
  prometheus:
    enabled: true
    path: /stillingsimport/internal/prometheus
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  envFrom:
    - secret: pam-import-api-env-secrets
  env:
    - name: DB_DRIVER
      value: org.postgresql.Driver
    - name: ADMINSTATUS_KAFKA_TOPIC
      value: teampam.stilling-intern-1
    - name: ANNONSEMOTTAK_TOPIC
      value: teampam.annonsemottak-v1
    - name: AD_OUTBOX_KAFKA_ENABLED
      value: "true"
    - name: AD_OUTBOX_SCHEDULER_ENABLED
      value: "true"
  accessPolicy:
    outbound:
      rules:
        - application: pam-ontologi
    inbound:
      rules:
        - application: pam-import-api-admin
        - application: toi-publisering-til-arbeidsplassen
          namespace: toi
