micronaut:
  application:
    name: import-api
  http:
    client:
      read-timeout: 300s
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: false
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
datasources:
  default:
    url: jdbc:h2:mem:devDb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
flyway:
  datasources:
    default:
      locations: classpath:db/migration
transferlog:
  size: 50
  delete:
    months: 6
  scheduler:
    enabled: true
shedlock:
  defaults:
    lock-at-most-for: 5m