micronaut:
  application:
    name: import
  server:
    port: 9028
    context-path: /stillingsimport
    thread-selection: auto
  http:
    client:
      read-timeout: 30s
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
      jdbc:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: false
  data:
    pageable:
      max-page-size: 1000
  security:
    enabled: true
    intercept-url-map:
      - pattern: ${micronaut.server.context-path}/swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: ${micronaut.server.context-path}/swagger-ui/**
        access:
          - isAnonymous()
      - pattern: ${micronaut.server.context-path}/frontend/**
        access:
          - isAnonymous()
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:Thisisaverylongsecretandcanonlybeusedintest}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
datasources:
  default:
    url: ${DB_JDBC_URL:`jdbc:tc:postgresql:14:///puls?TC_INITSCRIPT=postgres/postgres-init.sql`}
    driverClassName: ${DB_DRIVER:org.testcontainers.jdbc.ContainerDatabaseDriver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:''}
    maximum-pool-size: 8
    minimum-idle: 0
    pool-name: default
flyway:
  datasources:
    default:
      locations: classpath:db/migration
      #clean-on-validation-error: true
transferlog:
  batch-size: 100
  task-size: 500
  delete:
    months: 6
  scheduler:
    enabled: true
  adstate:
    kafka:
      enabled: false
pulsevent:
  kafka:
    enabled: true
    topic: teampam.puls-intern-2
adminstatussync:
  kafka:
    enabled: true
#    offsettimestamp: "2020-01-01T00:00:00Z"
  feedurl: ${PAM_AD_FEED_URL:`http://localhost:9001/api/v1/ads?source=IMPORTAPI`}
  pagesize: 200
shedlock:
  defaults:
    lock-at-most-for: 1m
ad:
  preview:
    url: ${AD_PREVIEW_URL:`http://localhost:8080/stillinger/intern`}
pam:
  ontologi:
    typeahead:
      url: http://pam-ontologi
azure:
  token_uri: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token}
  client-id: ${AZURE_APP_CLIENT_ID:3f89235b-1026-4f8d-a06b-d91b24316d2e}
  client-secret: ${AZURE_APP_CLIENT_SECRET:secret}
nais_cluster: ${NAIS_CLUSTER_NAME:dev-gcp}