micronaut:
  application:
    name: import-api
  server:
    port: 9028
    context-path: /importapi
  http:
    client:
      read-timeout: 300s
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: false
  data:
    pageable:
      max-page-size: 1000
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
datasources:
  default:
    url: ${ORACLE_JDBC_URL:`jdbc:h2:mem:devDb;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle`}
    driverClassName: ${ORACLE_DRIVER:org.h2.Driver}
    username: ${ORACLE_DB_USER:sa}
    password: ${ORACLE_DB_PASSWORD:''}
flyway:
  datasources:
    default:
      locations: classpath:db/migration
      clean-on-validation-error: true
transferlog:
  size: 50
  delete:
    months: 6
  scheduler:
    enabled: false
adminstatussync:
  scheduler:
    enabled: false
  feedurl: "http://localhost:9001/api/v1/ads"
  pagesize: 200
shedlock:
  defaults:
    lock-at-most-for: 1m

