micronaut:
  application:
    name: import-api
  server:
    port: 9028
    context-path: /stillingsimport
  http:
    client:
      read-timeout: 30s
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: false
  data:
    pageable:
      max-page-size: 1000
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:Thisisaverylongsecretandcanonlybeusedintest}
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false
jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true
datasources:
  default:
    url: ${ORACLE_JDBC_URL:`jdbc:h2:mem:devDb;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle`}
    driverClassName: ${ORACLE_DRIVER:org.h2.Driver}
    username: ${ORACLE_DB_USER:sa}
    password: ${ORACLE_DB_PASSWORD:''}
flyway:
  datasources:
    default:
      locations: classpath:db/migration
      #clean-on-validation-error: false
transferlog:
  batch-size: 500
  task-size: 500
  delete:
    months: 6
  scheduler:
    enabled: true
adminstatussync:
  scheduler:
    enabled: true
  kafka:
    enabled: false
#    offsettimestamp: "2020-01-01T00:00:00Z"
  feedurl: ${PAM_AD_FEED_URL:`http://localhost:9001/api/v1/ads?source=IMPORTAPI`}
  pagesize: 200
shedlock:
  defaults:
    lock-at-most-for: 1m
kafka:
  health:
    enabled: false
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9092`}

