
### Create provider
POST http://localhost:8080/internal/providers
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "identifier": "webcruiter",
  "email": "webcruiter@webcruiter.no",
  "phone": "12345678"
}

### Upload 2 ads for provider

POST http://localhost:8080/api/v1/transfers/1
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

< transfer-ads.json

### Get transfer info

GET http://localhost:8080/api/v1/transfers/1
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

### Get adstates

GET http://localhost:8080/api/v1/adstates/versions/1
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

### Get adstates by updated time

GET http://localhost:8080/api/v1/adstates/?updated=2020-02-27T08:34:50.000&page=0&size=1000&sort=updated,asc
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

###

