### Test scripts (Keys are only used for test purposes, wont work in prod)
### Create provider
POST http://localhost:9028/stillingsimport/internal/providers
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhcmJlaWRzcGxhc3Nlbi5uYXYubm8iLCJwcm92aWRlciI6MSwicm9sZXMiOiJST0xFX0FETUlOIiwiaXNzIjoiaHR0cHM6XC9cL2FyYmVpZHNwbGFzc2VuLm5hdi5ubyIsImp0aSI6IjJlZGVmYmY0LWUyNTgtNDUzOC1hYzMwLTY0NjhmZWUwMzQ0MSJ9.aIJsH2fOEq-4r38W75G5IV1HaLZ9KRi4bC2q4rBHt9U

{
  "identifier": "tester",
  "jwtid": "test-key-id-1",
  "email": "test@test.no",
  "phone": "12345678"
}

### New token for provider
PUT http://localhost:9028/stillingsimport/internal/providers/10000/token
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBhcmJlaWRzcGxhc3Nlbi5uYXYubm8iLCJwcm92aWRlciI6MSwicm9sZXMiOiJST0xFX0FETUlOIiwiaXNzIjoiaHR0cHM6XC9cL2FyYmVpZHNwbGFzc2VuLm5hdi5ubyIsImp0aSI6IjJlZGVmYmY0LWUyNTgtNDUzOC1hYzMwLTY0NjhmZWUwMzQ0MSJ9.aIJsH2fOEq-4r38W75G5IV1HaLZ9KRi4bC2q4rBHt9U

### Upload 2 ads for provider

POST http://localhost:9028/stillingsimport/api/v1/transfers/10000
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3Qubm8iLCJwcm92aWRlcklkIjoxLCJyb2xlcyI6IlJPTEVfUFJPVklERVIiLCJpc3MiOiJodHRwczpcL1wvYXJiZWlkc3BsYXNzZW4ubmF2Lm5vIiwiaWF0IjoxNTg1NjYxMDE4LCJqdGkiOiJ0ZXN0LWtleS1pZC0xIn0.ijVWV3gb3JDgIOvYr1yrdC0p2oIA-5dNp_-yQoqGeHM

< transfer-ads.json

### Upload 2 ads for provider using stream

POST http://localhost:9028/stillingsimport/api/v1/transfers/10000
Accept: application/x-json-stream
Cache-Control: no-cache
Content-Type: application/x-json-stream
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3Qubm8iLCJwcm92aWRlcklkIjoxLCJyb2xlcyI6IlJPTEVfUFJPVklERVIiLCJpc3MiOiJodHRwczpcL1wvYXJiZWlkc3BsYXNzZW4ubmF2Lm5vIiwiaWF0IjoxNTg1NjYxMDE4LCJqdGkiOiJ0ZXN0LWtleS1pZC0xIn0.ijVWV3gb3JDgIOvYr1yrdC0p2oIA-5dNp_-yQoqGeHM

< ads-stream.jstream

### Get transfer info

GET http://localhost:9028/stillingsimport/api/v1/transfers/10000/versions/1
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3ZWJjcnVpdGVyQHdlYmNydWl0ZXIubm8iLCJwcm92aWRlcklkIjoxLCJyb2xlcyI6IlJPTEVfUFJPVklERVIiLCJpc3MiOiJodHRwczpcL1wvYXJiZWlkc3BsYXNzZW4ubmF2Lm5vIiwianRpIjoiZDI3MDJmMmQtYzdkMy00ODZlLWFiZTQtN2ZiMGM5ZDRlNTA3In0.mxzEpDBfapZ8ku74enzq6_RFcnIq1-5XIIP0JfFrj04

### Get adstates

GET http://localhost:9028/stillingsimport/api/v1/adstates/versions/1
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

### Get adstates by updated time

GET http://localhost:9028/stillingsimport/api/v1/adstates/?updated=2020-02-27T08:34:50.000&page=0&size=1000&sort=updated,asc
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:9028/stillingsimport/api/v1/adminstatus/versions/1
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

###