name: tag-release
on:
  deployment_status:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: create tag and release
        if: github.event.deployment_status.state == 'success'
        uses: actions/checkout@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git tag -f $(cat .docker_tag)
          git push -f --tags
      - name: create changelog
        id: create_changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sinceTag: ${{ env.LATEST_TAG }}
          dueTag: $ {{ env.DOCKER_TAG }}
          stripGeneratorNotice: true
      - name: prepare change log
        run: |
          CHANGELOG=$(cat CHANGELOG.md)
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "::set-env name=CHANGE_LOG::$CHANGELOG"
      - name: draft release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ env.DOCKER_TAG }}
          release_name: Release ${{ env.DOCKER_TAG }}
          body: ${{ env.CHANGE_LOG }}
          draft: true
          prerelease: false